source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MakeColor_Example', :exclusive => true do
  pod 'MakeColor', :path => '../'
end

target 'MakeColor_Tests', :exclusive => true do
  pod 'MakeColor', :path => '../'

  
end
